#!/bin/bash

set -ex

export F90=gfortran
git clone --recursive https://github.com/msg-byu/enumlib.git
cd $HOME/enumlib
git checkout -b first_release v1.0.8
git submodule update
cd $HOME/enumlib/symlib/src
make
cd $HOME/enumlib/src
make
make enum.x
make makestr.x
mkdir -p $HOME/.local/bin
cp *.x $HOME/.local/bin/

cd $HOME
jupyter nbextension install --user --py pythreejs
jupyter nbextension enable --user --py pythreejs
jupyter serverextension enable --user --sys-prefix jupyter_server_proxy
jupyter serverextension enable --py nbzip --sys-prefix
jupyter nbextension install --user --py nbzip
jupyter nbextension enable --user --py nbzip
jupyter serverextension enable nbgitpuller --sys-prefix

cat server_proxy_config.py >> ${HOME}/.jupyter/jupyter_notebook_config.py
tar -xvzf ${HOME}/POTCARs.tar.gz -C ${HOME}
echo "PMG_VASP_PSP_DIR: $HOME/POTCARs" >> $HOME/.pmgrc.yaml
mkdir $HOME/mongodb

mkdir -pv $HOME/{log,lib,run}/munge $HOME/run/spool $HOME/run/slurm
PASSWORD=${1:-"Setec Astronomy"}
echo -n $PASSWORD | sha512sum | cut -d' ' -f1 > /tmp/munge.key
chmod go-rwx /tmp/munge.key
chmod +x $HOME/slurm-config.sh

git config --global user.email "jovyan@materialsproject.org"
#cd fireworks && pip install -e . && cd ..
pip install -e .

# MPContribs
git clone -b dev https://github.com/materialsproject/MPContribs.git
export SETUPTOOLS_SCM_PRETEND_VERSION=1.6.0
cd $HOME/MPContribs &&
    cd mpcontribs-client && pip install -e . && \
    cd ../mpcontribs-io && pip install -e . && \
    cd .. && npm install && \
    cp -v binder/binder.js . && \
    cp -v webpack-binder.config.js webpack.config.js && \
    npm run webpack && \
    rm -rf node_modules && \
    mkdir $HOME/.jupyter/custom && \
    mv -v dist $HOME/.jupyter/custom/js && \
    cp -v binder/custom.js $HOME/.jupyter/custom/
