#!/bin/bash

set -ex

export F90=gfortran
git clone --recursive https://github.com/msg-byu/enumlib.git
cd $HOME/enumlib
git checkout -b first_release v1.0.8
git submodule update
cd $HOME/enumlib/symlib/src
make
cd $HOME/enumlib/src
make
make enum.x
make makestr.x
mkdir -p $HOME/.enumlib
cp *.x $HOME/.enumlib
rm -Rf $HOME/enumlib

cd $HOME
#jupyter nbextension install --user --py pythreejs
#jupyter nbextension enable --user --py pythreejs
jupyter labextension install crystaltoolkit-extension
jupyter serverextension enable --py nbzip --sys-prefix
jupyter nbextension install --user --py nbzip
jupyter nbextension enable --user --py nbzip
jupyter serverextension enable nbgitpuller --sys-prefix

#tar -xvzf ${HOME}/POTCARs.tar.gz -C ${HOME}
#echo "PMG_VASP_PSP_DIR: $HOME/POTCARs" >> $HOME/.pmgrc.yaml
git config --global user.email "jovyan@materialsproject.org"
pip install -e .

mkdir $HOME/.mongodb
rm -rf ~/.cache
