#!/bin/bash

mongod --dbpath=$HOME/mongodb &
munged -f --key-file=/tmp/munge.key --pid-file=/tmp/munged.pid --socket=/tmp/munge.socket.2 --log-file=$HOME/log/munge/munged.log

export SLURM_CONF=$HOME/slurm.conf

if [ ! -s $SLURM_CONF ]; then
    name=`hostname -s`
    $HOME/slurm-config.sh $name $name CPUs=1
    echo "SlurmUser=$USER" >> $SLURM_CONF
    echo "SlurmdUser=$USER" >> $SLURM_CONF
    echo "SlurmdSpoolDir=$HOME/run/spool" >> $SLURM_CONF
    echo "SlurmctldPidFile=$HOME/run/slurmctld.pid" >> $SLURM_CONF
    echo "SlurmdPidFile=$HOME/run/slurmd.pid" >> $SLURM_CONF
    echo "StateSaveLocation=$HOME/slurm" >> $SLURM_CONF
    echo "$SLURM_CONF generated."
fi

slurmctld -c
slurmd -c
sinfo

[[ ! -e $HOME/mp_workshop/fireworks_config/FW_config.yaml ]] && python -c 'import mp_workshop.fireworks_config'

cd $HOME/lessons

exec "$@"
