#!/bin/bash

mongod --dbpath=$HOME/.mongodb &

python $HOME/binder/populate_nobel_database.py

cd $HOME/workshop/lessons

export PATH=$PATH:$HOME/.enumlib/

conda init bash
conda config --prepend pkgs_dirs $HOME/.conda/pkgs
conda activate notebook

exec "$@"
